// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "Hello world!",
    "about": "Go to the about page"
  },
  "AboutPage": {
    "title": "About this site",
    "home": "Go to the home page"
  }
};
export default messages;